name: Aseprite Build

on:
  
  schedule:
    - cron: '0 */3 * * *'  
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  fetch-aseprite-info:
    name: Fetch deps info
    runs-on: ubuntu-latest
    outputs:
      download-link: ${{ steps.aseprite-link.outputs.download-link }}
      release-tag: ${{ steps.aseprite-link.outputs.release-tag }}
    steps:
      - name: Fetch Aseprite release link
        id: aseprite-link
        uses: a1393323447/fetch-release@main
        with:
            group: aseprite
            repo: aseprite
            match: Aseprite-.*?-Source.zip

  build-aseprite-ci:
    name: Build Aseprite (CI)
    needs: fetch-aseprite-info
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Aseprite
        shell: bash
        run: |
          git clone --recurse-submodules -j8 https://github.com/aseprite/aseprite --branch ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          
      - name: Install Skia (Windows)
        working-directory: aseprite
        shell: bash
        run: |
          choco install wget -y --no-progress
          wget https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia
          
      - uses: aseprite/get-ninja@main
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Generating Makefiles
        shell: bash
        working-directory: aseprite
        run: |
          cmake -S . -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
            -DENABLE_TESTS=OFF `
            -DENABLE_SCRIPTING=ON `
            -DENABLE_CCACHE=OFF `
            -DLAF_BACKEND=skia `
            -DSKIA_DIR=$(realpath skia) `
            -DOPENSSL_USE_STATIC_LIBS=ON `
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)
            
      - name: Compiling
        shell: bash
        working-directory: aseprite
        run: |
          cd build && ninja
          
      - name: Clean Up Build folder
        working-directory: aseprite/build/bin
        shell: bash
        run: |
          
          Get-ChildItem | Where-Object { 
            $_.Name -notin @('aseprite.exe', 'data') -and $_.Name -notlike '*.dll'
          } | Remove-Item -Recurse -Force
          
      - name: Make portable zip
        working-directory: aseprite/build/bin
        run: |
          echo '# This file is here so Aseprite behaves as a portable program' > aseprite.ini
          
      - name: Create CI build zip
        working-directory: aseprite/build/bin
        run: |
          7z -tzip a Aseprite-CI-${{ needs.fetch-aseprite-info.outputs.release-tag }}-Windows.zip *
          
      - name: Upload CI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite-CI-Windows-${{ needs.fetch-aseprite-info.outputs.release-tag }}
          path: aseprite/build/bin/Aseprite-CI-${{ needs.fetch-aseprite-info.outputs.release-tag }}-Windows.zip
          retention-days: 7  

  build-aseprite-release:
    name: Build Aseprite (Release)
    needs: fetch-aseprite-info
    
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 0 1 * *'
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Aseprite
        shell: bash
        run: |
          git clone --recurse-submodules -j8 https://github.com/aseprite/aseprite --branch ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          
      - name: Install Skia (Windows)
        working-directory: aseprite
        shell: bash
        run: |
          choco install wget -y --no-progress
          wget https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia
          
      - uses: aseprite/get-ninja@main
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Generating Makefiles
        shell: bash
        working-directory: aseprite
        run: |
          cmake -S . -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
            -DENABLE_TESTS=OFF `
            -DENABLE_SCRIPTING=ON `
            -DENABLE_CCACHE=OFF `
            -DLAF_BACKEND=skia `
            -DSKIA_DIR=$(realpath skia) `
            -DOPENSSL_USE_STATIC_LIBS=ON `
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)
            
      - name: Compiling
        shell: bash
        working-directory: aseprite
        run: |
          cd build && ninja
          
      - name: Clean Up Build folder
        working-directory: aseprite/build/bin
        shell: bash
        run: |
          
          Get-ChildItem | Where-Object { 
            $_.Name -notin @('aseprite.exe', 'data') -and $_.Name -notlike '*.dll'
          } | Remove-Item -Recurse -Force
          
      - name: Make portable zip
        working-directory: aseprite/build/bin
        run: |
          echo '# This file is here so Aseprite behaves as a portable program' > aseprite.ini
          
      - name: Create Release zip
        working-directory: aseprite/build/bin
        run: |
          7z -tzip a Aseprite-${{ needs.fetch-aseprite-info.outputs.release-tag }}-Windows.zip *
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          name: Aseprite ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          body: |
            Aseprite ${{ needs.fetch-aseprite-info.outputs.release-tag }} - Windows Build
            Auto-built release version.
          artifacts: aseprite/build/bin/Aseprite-${{ needs.fetch-aseprite-info.outputs.release-tag }}-Windows.zip
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}
